# Generated by Django 6.0.5 on 2026-05-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_institute_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
