# Generated by Django 6.0.5 on 2026-05-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_institute_app', '0002_user_google_picture'),
    ]

    operations = [
    ]
