# Generated by Django 6.0.5 on 2026-05-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_institute_app', '0004_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program_structure',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_master',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='who_should_attend',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
