# Generated by Django 6.0.5 on 2026-05-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_institute_app', '0005_course_program_structure_course_what_you_will_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
    ]
