# Generated by Django 6.0.5 on 2026-05-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_institute_app', '0006_remove_course_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_line1', models.CharField(max_length=200)),
                ('hero_title_line2', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField()),
                ('hero_badge_text', models.CharField(max_length=50)),
                ('hero_badge_icon', models.CharField(max_length=50)),
                ('mission_vision_items', models.JSONField()),
                ('timeline_items', models.JSONField()),
                ('team_members', models.JSONField()),
                ('statistics', models.JSONField()),
                ('why_us_features', models.JSONField()),
                ('show_mission_vision', models.BooleanField(default=True)),
                ('show_timeline', models.BooleanField(default=True)),
                ('show_leadership', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('show_why_us', models.BooleanField(default=True)),
                ('timeline_section_tag', models.CharField(max_length=50)),
                ('timeline_section_title', models.CharField(max_length=200)),
                ('timeline_section_subtitle', models.TextField()),
                ('leadership_section_tag', models.CharField(max_length=50)),
                ('leadership_section_title', models.CharField(max_length=200)),
                ('leadership_section_subtitle', models.TextField()),
                ('why_us_section_tag', models.CharField(max_length=50)),
                ('why_us_section_title', models.CharField(max_length=200)),
                ('why_us_section_subtitle', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
